### ISSUE TITLE
Can't seem to boot server after adding mod

### ISSUE THREAD

**Issue by xDraxxis** [DrexHD/FabricAntiXray#4]
Tried with and without my server's mods. Won't boot at all. The latest version of Fabric and Fabric API. 1.0.1 of Anti-Xray

`
[19:45:23] [main/INFO]: Loading for game Minecraft 1.17.1
[19:45:23] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution failed!
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:828) ~[fabric.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric.jar:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to open mod JAR at /opt/dev/mods/anti-xray-1.0.1.jar!
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:605) ~[?:?]
        at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:938) ~[?:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:808) ~[fabric.jar:?]
        ... 11 more
Caused by: java.lang.RuntimeException: Failed to open mod JAR at /opt/dev/mods/anti-xray-1.0.1.jar!
        at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:640) ~[fabric.jar:?]
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
`

**Comment by xDraxxis** [comment]
Looks like the file on Modrinth is just empty, downloaded latest from actions and it worked fine.
